//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomenProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomData
    {
        public int ID { get; set; }
        public string SNAME { get; set; }
        public string FNAME { get; set; }
        public Nullable<int> ITEM_CNT { get; set; }
        public Nullable<int> CNT_TYPE { get; set; }
    
        public virtual nomcount_types nomcount_types { get; set; }
    }
}
